// Generated by Dagger (https://dagger.dev).
package com.footballfan.ui.football.leaguedetailmain;

import dagger.internal.Factory;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class DetailMainPresenter_Factory implements Factory<DetailMainPresenter> {
  @Override
  public DetailMainPresenter get() {
    return newInstance();
  }

  public static DetailMainPresenter_Factory create() {
    return InstanceHolder.INSTANCE;
  }

  public static DetailMainPresenter newInstance() {
    return new DetailMainPresenter();
  }

  private static final class InstanceHolder {
    private static final DetailMainPresenter_Factory INSTANCE = new DetailMainPresenter_Factory();
  }
}
