// Generated by Dagger (https://dagger.dev).
package com.footballfan.ui.football.leaguedetailmain;

import dagger.internal.Factory;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class DetailMainViewModel_Factory implements Factory<DetailMainViewModel> {
  private final Provider<DetailMainPresenter> detailMainPresenterProvider;

  public DetailMainViewModel_Factory(Provider<DetailMainPresenter> detailMainPresenterProvider) {
    this.detailMainPresenterProvider = detailMainPresenterProvider;
  }

  @Override
  public DetailMainViewModel get() {
    return newInstance(detailMainPresenterProvider.get());
  }

  public static DetailMainViewModel_Factory create(
      Provider<DetailMainPresenter> detailMainPresenterProvider) {
    return new DetailMainViewModel_Factory(detailMainPresenterProvider);
  }

  public static DetailMainViewModel newInstance(DetailMainPresenter detailMainPresenter) {
    return new DetailMainViewModel(detailMainPresenter);
  }
}
