// Generated by Dagger (https://dagger.dev).
package com.footballfan.ui.football.leaguelist;

import dagger.internal.Factory;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class LeagueListViewModel_Factory implements Factory<LeagueListViewModel> {
  private final Provider<LeagueListPresenter> leagueListPresenterProvider;

  public LeagueListViewModel_Factory(Provider<LeagueListPresenter> leagueListPresenterProvider) {
    this.leagueListPresenterProvider = leagueListPresenterProvider;
  }

  @Override
  public LeagueListViewModel get() {
    return newInstance(leagueListPresenterProvider.get());
  }

  public static LeagueListViewModel_Factory create(
      Provider<LeagueListPresenter> leagueListPresenterProvider) {
    return new LeagueListViewModel_Factory(leagueListPresenterProvider);
  }

  public static LeagueListViewModel newInstance(LeagueListPresenter leagueListPresenter) {
    return new LeagueListViewModel(leagueListPresenter);
  }
}
