// Generated by Dagger (https://dagger.dev).
package com.footballfan.ui.football.leaguelist;

import com.footballfan.domain.FootballInteractor;
import dagger.internal.Factory;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class LeagueListPresenter_Factory implements Factory<LeagueListPresenter> {
  private final Provider<FootballInteractor> footballInteractorProvider;

  public LeagueListPresenter_Factory(Provider<FootballInteractor> footballInteractorProvider) {
    this.footballInteractorProvider = footballInteractorProvider;
  }

  @Override
  public LeagueListPresenter get() {
    return newInstance(footballInteractorProvider.get());
  }

  public static LeagueListPresenter_Factory create(
      Provider<FootballInteractor> footballInteractorProvider) {
    return new LeagueListPresenter_Factory(footballInteractorProvider);
  }

  public static LeagueListPresenter newInstance(FootballInteractor footballInteractor) {
    return new LeagueListPresenter(footballInteractor);
  }
}
