// Generated by Dagger (https://dagger.dev).
package com.footballfan.ui.news.deatilnews;

import dagger.internal.Factory;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class DetailNewsViewModel_Factory implements Factory<DetailNewsViewModel> {
  private final Provider<DetailNewsPresenter> detailnewspresenterProvider;

  public DetailNewsViewModel_Factory(Provider<DetailNewsPresenter> detailnewspresenterProvider) {
    this.detailnewspresenterProvider = detailnewspresenterProvider;
  }

  @Override
  public DetailNewsViewModel get() {
    return newInstance(detailnewspresenterProvider.get());
  }

  public static DetailNewsViewModel_Factory create(
      Provider<DetailNewsPresenter> detailnewspresenterProvider) {
    return new DetailNewsViewModel_Factory(detailnewspresenterProvider);
  }

  public static DetailNewsViewModel newInstance(DetailNewsPresenter detailnewspresenter) {
    return new DetailNewsViewModel(detailnewspresenter);
  }
}
