// Generated by Dagger (https://dagger.dev).
package com.footballfan.ui.news.deatilnews;

import dagger.internal.Factory;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class DetailNewsPresenter_Factory implements Factory<DetailNewsPresenter> {
  @Override
  public DetailNewsPresenter get() {
    return newInstance();
  }

  public static DetailNewsPresenter_Factory create() {
    return InstanceHolder.INSTANCE;
  }

  public static DetailNewsPresenter newInstance() {
    return new DetailNewsPresenter();
  }

  private static final class InstanceHolder {
    private static final DetailNewsPresenter_Factory INSTANCE = new DetailNewsPresenter_Factory();
  }
}
