// Generated by Dagger (https://dagger.dev).
package com.footballfan.ui.auth.register;

import dagger.internal.Factory;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class RegisterViewModel_Factory implements Factory<RegisterViewModel> {
  private final Provider<RegisterPresenter> registerPresenterProvider;

  public RegisterViewModel_Factory(Provider<RegisterPresenter> registerPresenterProvider) {
    this.registerPresenterProvider = registerPresenterProvider;
  }

  @Override
  public RegisterViewModel get() {
    return newInstance(registerPresenterProvider.get());
  }

  public static RegisterViewModel_Factory create(
      Provider<RegisterPresenter> registerPresenterProvider) {
    return new RegisterViewModel_Factory(registerPresenterProvider);
  }

  public static RegisterViewModel newInstance(RegisterPresenter registerPresenter) {
    return new RegisterViewModel(registerPresenter);
  }
}
